# Generated by Django 4.2.5 on 2023-11-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderedfood_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedFood',
        ),
    ]
