# Generated by Django 4.2.5 on 2023-11-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderedfood_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfood',
            name='order',
        ),
    ]
