# Generated by Django 4.2.5 on 2023-11-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='restuarant_name',
            new_name='restaurant_name',
        ),
    ]
